export default interface OrderAttributes {
  _approve: boolean
  _billing_address_clone_id: string
  _billing_address_same_as_shipping: boolean
  _cancel: boolean
  _capture: boolean
  _customer_payment_source_id: string
  _place: boolean
  _refresh: boolean
  _refund: boolean
  _saveBilling_address_to_customer_address_book: boolean
  _save_payment_source_to_customer_wallet: boolean
  _save_shipping_address_to_customer_address_book: boolean
  _shipping_address_clone_id: string
  _shipping_address_same_as_billing: boolean
  _update_taxes: boolean
  adjustment_amount_cents: number
  adjustment_amount_float: number
  adjustment_tax_amount_cents: number
  adjustment_tax_amount_float: number
  approved_at: string
  archived_at: string
  cancelled_at: string
  cart_url: string
  checkout_url: string
  country_code: string
  coupon_code: string
  created_at: string
  currency_code: string
  customer_email: string
  customer_password: string
  discount_amount_cents: number
  discount_amount_float: number
  discount_tax_amount_cents: number
  discount_tax_amount_float: number
  discount_taxable_amount_cents: number
  discount_taxable_amount_float: number
  editable: boolean
  fees_amount_cents: number
  fees_amount_float: number
  formatted_adjustment_amount: string
  formatted_adjustment_tax_amount: number
  formatted_discount_amount: string
  formatted_discount_tax_amount: string
  formatted_discount_taxable_amount: string
  formatted_fees_amount: string
  formatted_gift_card_amount: string
  formatted_payment_method_amount: string
  formatted_payment_method_tax_amount: string
  formatted_payment_method_taxable_amount: string
  formatted_shipping_amount: string
  formatted_shipping_tax_amount: string
  formatted_shipping_taxable_amount: string
  formatted_subtotal_amount: string
  formatted_subtotal_tax_amount: string
  formatted_subtotal_taxable_amount: string
  formatted_total_amount: string
  formatted_total_amount_with_taxes: string
  formatted_total_tax_amount: string
  formatted_total_taxable_amount: string
  freight_taxable: boolean
  fulfillment_status: string
  fulfillment_updated_at: string
  gift_card_amount_cents: number
  gift_card_amount_float: number
  gift_card_code: string
  gift_card_or_coupon_code: string
  guest: boolean
  id: string
  language_code: string
  line_item_options_count: number
  metadata: object
  number: number
  payment_method_amount_cents: number
  payment_method_amount_float: number
  payment_method_tax_amount_cents: number
  payment_method_tax_amount_float: number
  payment_method_taxable_amount_cents: number
  payment_method_taxable_amount_float: number
  payment_source_details: object
  payment_source_id: string
  payment_source_type: string
  payment_status: string
  payment_updated_at: string
  placeable: boolean
  placed_at: string
  privacy_url: string
  reference: string
  reference_origin: string
  return_url: string
  shipments_count: number
  shipping_amount_cents: number
  shipping_amount_float: number
  shipping_country_code_lock: string
  shipping_tax_amount_cents: number
  shipping_tax_amount_float: number
  shipping_taxable_amount_cents: number
  shipping_taxable_amount_float: number
  skus_count: string
  status: string
  subtotal_amount_cents: number
  subtotal_amount_float: number
  subtotal_tax_amount_cents: number
  subtotal_tax_amount_float: number
  subtotal_taxable_amount_cents: number
  subtotal_taxable_amount_float: number
  tax_included: boolean
  tax_rate: number
  terms_url: string
  token: string
  total_amount_cents: number
  total_amount_float: number
  total_amount_with_taxes_cents: number
  total_amount_with_taxes_float: number
  total_tax_amount_cents: number
  total_tax_amount_float: number
  total_taxable_amount_cents: number
  total_taxable_amount_float: number
  updated_at: string
}
