name: Release
on:
  push:
    branches: [master, beta, alpha]
  pull_request:
    branches: [master, beta, alpha]
jobs:
  release:
    name: Release
    environment: staging
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Run package
        run: npm run build
      # - name: Run specs
      #   env:
      #     ENDPOINT: ${{ secrets.ENDPOINT }}
      #     SALES_CHANNEL_ID: ${{ secrets.SALES_CHANNEL_ID }}
      #     CLIENT_ID: ${{ secrets.CLIENT_ID}}
      #     CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      #     SCOPE: ${{ secrets.SCOPE}}
      #     WEBAPP_CLIENT_ID: ${{ secrets.WEBAPP_CLIENT_ID }}
      #     WEBAPP_CLIENT_SECRET: ${{ secrets.WEBAPP_CLIENT_SECRET}}
      #     CALLBACK_URL: ${{ secrets.CALLBACK_URL}}
      #   run: npm test
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
